### ISSUE TITLE
AudioTools 1.2.4 URLStream.h fails to compile on ESP32-S3 (Arduino 2.0.17): setConnectionTimeout() not found

### ISSUE THREAD

**Issue by eferbel** [pschatzmann/arduino-audio-tools#2367]
### Problem Description

Building a project that uses AudioTools URLStream on ESP32-S3 fails because URLStream.h calls:

client_secure->setConnectionTimeout(...)
client_insecure->setConnectionTimeout(...)

However, WiFiClientSecure and WiFiClient in the ESP32 Arduino framework do not provide this method and compilation fails with:

'class WiFiClientSecure' has no member named 'setConnectionTimeout'
'class WiFiClient' has no member named 'setConnectionTimeout'

Replacing setConnectionTimeout() with setTimeout() allows the project to compile and work correctly.

AudioTools version: 1.2.4
Audio Driver version: 0.2.1
PlatformIO espressif32: 6.9.0
ESP32 Arduino Framework: 2.0.17

### Device Description

Board: ESP32-S3-DevKitC-1-N16R8V
Flash: 16 MB
PSRAM: 8 MB
Framework: Arduino
PlatformIO: espressif32 6.9.0
Arduino Core: 2.0.17

### Sketch

```cpp
PlatformIO configuration

[env:esp32s3_test]
platform = espressif32 @ 6.9.0
framework = arduino
board = esp32-s3-devkitc-1-n16r8v

lib_deps =
    WiFi
    WiFiClientSecure
    https://github.com/pschatzmann/arduino-audio-tools.git#v1.2.4

Minimal sketch

#include <Arduino.h>
#include <WiFi.h>
#include <AudioTools.h>
#include <AudioTools/Communication/AudioHttp.h>

audio_tools::URLStream urlStream;

void setup() {
}

void loop() {
}

Compiler output

URLStream.h:362:24: error:
'class WiFiClientSecure' has no member named 'setConnectionTimeout'

URLStream.h:376:24: error:
'class WiFiClient' has no member named 'setConnectionTimeout'

Expected behavior

AudioTools should compile successfully with ESP32 Arduino framework 2.0.17.

Workaround

Replacing

setConnectionTimeout(...)

with

setTimeout(...)

in URLStream.h allows the project to compile correctly.
```

### I have checked existing issues, discussions and online documentation (incl. the Wiki)

- [x] I confirm I have checked existing issues, discussions and online documentation

**Comment by pschatzmann** [comment]
I committed a correction: However you shouln't really use this old release any more: the actual version is not 2.0.17 but 3.3.10 with 4.0 coming out soon!

**Comment by eferbel** [comment]
Thank you for your prompt response.

URLStream.h line 363 appears to use client_insecure instead of client_secure inside the secure client initialization block. Is this correct?

**Comment by pschatzmann** [comment]
good catch!
