### PR TITLE
Only define variables in cpp files

### PR DESCRIPTION
**Pull request by roleroz**
If you have multiple compilation units (like libraries compiled separately), each of them will include these files and define these variables. After this, linking with fail with multiple definitions for the variables

This might be happening on other places, but fixed the ones I found

I'm not 100% sure how to test this in Arduino, it works well in PlatformIO

### CODE REVIEW

**Comment by pschatzmann** [comment]
Since this is a header only library I do not accept any cpp files.
Change the definition to static! that should resolve the issue as well...

**Comment by roleroz** [comment]
Done, and it works :D

Out of curiosity, why is this library a header only library?, Arduino recommendations have both headers and cpp files

**Comment by pschatzmann** [comment]
I am used to programming in some modern languages, and I just did not want to go back to this old programming model which is just a pain if you need to change something.

In Arduino and PlatformIO it does not make a difference, but in other environments it simplifies the build process. You don't need to build the library, and you don't need to specify the compiled library during the link step of the build. E.g. you can run this in Jupyter w/o compiling.

**Comment by joba-1** [comment]
> it works

I guess that depends on the use case.

Like this it creates a variable for each compilation unit (outside Arduino land) that includes the header and that might lead to nicely hidden bugs where you think the content should be the same but isn’t.

A public static member of a class could be a better choice.

**Comment by pschatzmann** [comment]
To resolve this issue correctly we would need to extend the callback methods in the class provided in the libhelix project, to provide an additional parameter that would pass the caller.

I am not sure however if this is really an issue because it is quite impossible to have more the one instantiation of a libhelix due to the limited memory on micro controllers.

**Comment by pschatzmann** [comment]
I have changed the functionality in libhelix and the audiotools, so that no global variable is necessary any more for this case!
