### ISSUE TITLE
streams-sd_mp3-audiokit.ino not compiling with Typo error "singal_type" in I2SCodecStream.h

### ISSUE THREAD

**Issue by cofiemark** [pschatzmann/arduino-audio-tools#2051]
### Problem Description

Streams-SD_MP3-Audiokit not compiling with Typo error of "singal_type" in I2SCodecStream.h
**Error Messages attached**
In file included from ~/Arduino/libraries/arduino-audio-tools/src/AudioTools/AudioLibs/AudioBoardStream.h:4,
                 from ~/Arduino/streams_sd_mp3_audiokit/streams_sd_mp3_audiokit.ino:14:

~/Arduino/libraries/arduino-audio-tools/src/AudioTools/AudioLibs/I2SCodecStream.h: In member function 'bool audio_tools::I2SCodecStream::beginCodec(audio_tools::I2SCodecConfig)':

~/Arduino/libraries/arduino-audio-tools/src/AudioTools/AudioLibs/I2SCodecStream.h:306:19: error: 'struct audio_driver::I2SDefinition' has no member named **'signal_type'**; did you mean **'singal_type'**?

  **306 |     codec_cfg.i2s.signal_type = (signal_t) info.signal_type;**
      |                   ^~~~~~~~~~~
      |                   singal_type
~/Arduino/libraries/arduino-audio-tools/src/AudioTools/AudioLibs/I2SCodecStream.h:306:34: error: 'signal_t' was not declared in this scope; did you mean 'signal'?

  **306 |     codec_cfg.i2s.signal_type = (signal_t) info.signal_type;**
      |                                  ^~~~~~~~
      |                                  signal
exit status 1

Compilation error: exit status 1

### Device Description

ESP32-A1S AudioKitEs8388V1 v2.2

### Sketch

```cpp
/**
 * @file streams-sd-audiokit.ino
 * @author Phil Schatzmann
 * @brief Just a small demo, how to use files with the SD library
 * @version 0.1
 * @date 2022-10-09
 * 
 * @copyright Copyright (c) 2022
 * 
 */
#include <SPI.h>
#include <SD.h>
#include "AudioTools.h"
#include "AudioTools/AudioLibs/AudioBoardStream.h"
#include "AudioTools/AudioCodecs/CodecMP3Helix.h"


const int chipSelect=PIN_AUDIO_KIT_SD_CARD_CS;
AudioBoardStream i2s(AudioKitEs8388V1); // final output of decoded stream
EncodedAudioStream decoder(&i2s, new MP3DecoderHelix()); // Decoding stream
StreamCopy copier; 
File audioFile;

void setup(){
  Serial.begin(115200);
  AudioToolsLogger.begin(Serial, AudioToolsLogLevel::Info);  

  // setup audiokit before SD!
  auto config = i2s.defaultConfig(TX_MODE);
  config.sd_active = true;
  i2s.begin(config);

  // setup file
  SD.begin(chipSelect);
  audioFile = SD.open("/0004ANUNYAM.mp3");

  // setup I2S based on sampling rate provided by decoder
  decoder.begin();

  // begin copy
  copier.begin(decoder, audioFile);

}

void loop(){
  if (!copier.copy()) {
    stop();
  }
}
```

### Other Steps to Reproduce

Tried to compile on MacOS 13.41 with Arduino IDE

### What is your development environment (incl. core version info)

Arduino IDE v2.3.5

### I have checked existing issues, discussions and online documentation

- [x] I confirm I have checked existing issues, discussions and online documentation

**Comment by pschatzmann** [comment]
This has already been answered multiple times
